version: 2
jobs:
  "python-2.7":
    docker:
      - image: circleci/python:2.7
    working_directory: ~/rio-cogeo
    steps:
      - checkout
      - run: sudo pip install -U pip
      - run: sudo pip install virtualenv
      - run: virtualenv venv
      - run:
          command: |
            . venv/bin/activate
            pip install -q -e .[test]
            python -m pytest --cov rio_cogeo --cov-report term-missing --ignore=venv

  "python-3.6":
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/rio-cogeo
    steps:
      - checkout
      - run: sudo pip3 install -U pip
      - run: python3 -m venv venv
      - run:
          command: |
            . venv/bin/activate
            pip3 install -q -e .[test]
            python3 -m pytest --cov rio_cogeo --cov-report term-missing --ignore=venv

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
