version: 2
common: &common
  - run:
    name: install dependencies
    command: pip install tox codecov pre-commit --user
  - run:
    name: run tox
    command: ~/.local/bin/tox

jobs:
  "python-2.7":
    working_directory: ~/rio-cogeo
    docker:
      - image: circleci/python:2.7
        environment:
          - TOXENV=py27
    steps:
      - checkout
      - *common

  "python-3.6":
    working_directory: ~/rio-cogeo
    docker:
      - image: circleci/python:3.6.5
        environment:
          - TOXENV=py36
          - UPLOAD_COVERAGE=1
    steps:
      - checkout
      - *common
      - run:
          name: run pre-commit
          command: |
            ~/.local/bin/pre-commit run --all-files
      - run:
          name: upload coverage report
          command: |
            ~/.local/bin/coverage xml
            ~/.local/bin/codecov

  "python-3.7":
    working_directory: ~/rio-cogeo
    docker:
      - image: circleci/python:3.7.2
        environment:
          - TOXENV=py37
    steps:
      - checkout
      - *common

  deploy:
    working_directory: ~/rio-cogeo
    docker:
      - image: circleci/python:3.7.2
        environment:
          - TOXENV=release
    steps:
      - checkout
      - run:
          name: verify git tag vs. version
          command: |
            VERSION=$(python setup.py --version)
            if [ "$VERSION" = "$CIRCLE_TAG" ]; then exit 0; else exit 3; fi
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - *common

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7":
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploy:
          requires:
            - "python-3.7"
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/